apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-pipeline-workspace
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 